### ISSUE TITLE
I cant login and register

### ISSUE THREAD

**Issue by nonameclub** [ketanchoyal/Academic-Connect#12]
Can you give me database structere, can you export firebase database?

**Comment by kzawadi** [comment]
The Database structure is provider and very visible to-date @ketanchoyal  has updated the repo structure...to help you with the logic of login  just deal with the login flow as shown in the dbstructure folder (it contains picture of almost every steps)    and you will be able to login
Duplicate of #9

**Comment by cradlesnatcher** [comment]
@nonameclub  close this issue
