### ISSUE TITLE
What is the School Name Code to used ?

### ISSUE THREAD

**Issue by Mike4ftv** [ketanchoyal/Academic-Connect#3]
Hello,
Thanks for share this app model.
Could you give me please the code school to used ? because I am on the create account page and I am can't go after...
Thanks

**Comment by ketanchoyal** [comment]
you can't add your school to this app as I haven't added my json files to connect with firebase

**Comment by Baksman** [comment]
so u mean its not possible to login?? its demanding school code

**Comment by kzawadi** [comment]
the repo is updated with the db structure    ..you have to structure firebase like that in order to login

**Comment by kzawadi** [comment]
please do check #6
