### ISSUE TITLE
register/login

### ISSUE THREAD

**Issue by 926** [ketanchoyal/Academic-Connect#4]
Hello, super cool to share this project ! Curious to see more.
I update .json accordingly and tried to run it.
Got stuck on the register/login screen.
After filling **register** form and submit, screen freezes.
Please could you show the way in order to pass the first screen ?

Test version could also have a fake profile so potential client see key functionalities early.
And then choose wether to build upon this repo.

**Comment by 926** [comment]
![Capture d’écran 2020-01-28 à 11 39 26](https://user-images.githubusercontent.com/14161798/73256779-dcace280-41c2-11ea-849e-cdbc83a85615.png)
![Capture d’écran 2020-01-28 à 11 39 17](https://user-images.githubusercontent.com/14161798/73256780-dd457900-41c2-11ea-8dca-1eb8e0e9fb7f.png)

**Comment by Baksman** [comment]
trying to sign up showing school name code not registered how can i register one???

**Comment by su-khi** [comment]
You'll have to set-up the Firebase FireStore collections. Something like this :
<img width="1049" alt="Screenshot 2020-01-31 at 20 51 41" src="https://user-images.githubusercontent.com/30054678/73550957-857d6b00-446b-11ea-9953-f431958da924.png">

**Comment by 926** [comment]
Thank you for feedback,
And also for adding screenshots, but it lack the interactive appeal.
I copied your screenshot in firebase, but still could not go pass beyond the register/login screen.

What a pity : /

**Comment by su-khi** [comment]
What do you want in the interactive appeal ? 

Mate, first of all, this is not the "issue" with the code. You are supposed to reverse engineer the code so as to find the database structure. You might want to contact the author if you need any help.

By the way, the following two screen-shots will help you to get past the sign-up screen.

<img width="1083" alt="Screenshot 2020-02-05 at 16 59 01" src="https://user-images.githubusercontent.com/30054678/73838214-2fc50c00-4839-11ea-8093-2afe996a2823.png">

<img width="1079" alt="Screenshot 2020-02-05 at 16 59 48" src="https://user-images.githubusercontent.com/30054678/73838221-33589300-4839-11ea-9ac0-95ac97a431b1.png">

**Comment by su-khi** [comment]
The following screenshot will is the DB structure to hold profiles.

<img width="1078" alt="Screenshot 2020-02-05 at 17 02 38" src="https://user-images.githubusercontent.com/30054678/73838296-61d66e00-4839-11ea-828a-d1b1ee5fbc69.png">


Hope this helps.

**Comment by 926** [comment]
Thank you for providing these screenshots,
Indeed these are not issues, but it greatly eases onboarding.
Is there a way to quickly set-up the Firebase DB ? Such as copy pasting a test file or providing copy-paste guidelines in the read me ?

**Comment by su-khi** [comment]
Please google, make some trials, if no success then post the question to StackOverflow :) Please close the issue if you can or request the author to close this issue.

**Comment by ketanchoyal** [comment]
@926 I've pushed DB Structure on git you can check it
