### ISSUE TITLE
not able to login

### ISSUE THREAD

**Issue by anandgp** [ketanchoyal/Academic-Connect#6]
fixed the DB exactly as in the DB structure screenshots still not able to log in. always showing school code not found @ketanchoyal please help me to resolve this issue

**Comment by kzawadi** [comment]
share your db structure so we can look at what is wrong with your implementation

**Comment by anandgp** [comment]
I replicated exactly the same as the structure provided in the git source


![Screenshot (17)](https://user-images.githubusercontent.com/25168655/75228329-f8150880-57d5-11ea-8183-90bdd6eb6b10.png)
![Screenshot (18)](https://user-images.githubusercontent.com/25168655/75228355-02370700-57d6-11ea-8df4-40712887c9b1.png)
![Screenshot (19)](https://user-images.githubusercontent.com/25168655/75228376-0b27d880-57d6-11ea-8087-f3d15a2b5185.png)
![Screenshot (20)](https://user-images.githubusercontent.com/25168655/75228396-124ee680-57d6-11ea-97c5-3cbfa39945f6.png)
![Screenshot (21)](https://user-images.githubusercontent.com/25168655/75228418-1aa72180-57d6-11ea-997a-b47f60733498.png)
![Screenshot (22)](https://user-images.githubusercontent.com/25168655/75228434-2397f300-57d6-11ea-9830-2774fde63ebc.png)
![Screenshot (23)](https://user-images.githubusercontent.com/25168655/75228465-27c41080-57d6-11ea-9327-62f2204f0245.png)

**Comment by kzawadi** [comment]
okay i hope your have setup the connection to your firebase project correctly ...the problem according to your structure i think is case sensitivity in {schools}  make it {Schools} CAPITAL LETTER S......and you don't have to create all the files as shown there ...just Schools/ABCD/Login/ Students 0r Teachers/Parents and its contents just as you have structured.....

**Comment by anandgp** [comment]
> okay i hope your have setup the connection to your firebase project correctly ...the problem according to your structure i think is case sensitivity in {schools} make it {Schools} CAPITAL LETTER S......and you don't have to create all the files as shown there ...just Schools/ABCD/Login/ Students 0r Teachers/Parents and its contents just as you have structured.....

no bro it's still the same.

**Comment by kzawadi** [comment]
what error do you got in debug when trying to signup

**Comment by anandgp** [comment]
> what error do you got in debug when trying to signup

"No school with that code found"

**Comment by kzawadi** [comment]
And have you enabled email auth in firebase console and putted the .json in app level Gradle

**Comment by su-khi** [comment]
Try to give a hard-coded path and check if it works.

**Comment by anandgp** [comment]
> And have you enabled email auth in firebase console and putted the .json in app level Gradle

yes, already enabled and google json is in place

**Comment by anandgp** [comment]
> Try to give a hard-coded path and check if it works.

not able to locate the path inside the program

**Comment by su-khi** [comment]
@anandgp - Please debug and find-out the place. Then check with hardcoded school-code. If it works then it means the problem is within the DB set-up, else with the connection. There's nothing wrong in code written by @ketanchoyal. It works perfectly well w.r.t. sign-up and login. Good luck !

**Comment by anandgp** [comment]
> @anandgp - Please debug and find-out the place. Then check with hardcoded school-code. If it works then it means the problem is within the DB set-up, else with the connection. There's nothing wrong in code written by @ketanchoyal. It works perfectly well w.r.t. sign-up and login. Good luck !

@su-khi  yes the code is perfectly fine, the DB structure is what am having an issue with I think
code os \

**Comment by kzawadi** [comment]
https://github.com/ketanchoyal/Academic-Connect/blob/05caa4024959f3e9acae1272a0a1adeff518f225/lib/core/services/AuthenticationServices.dart#L80



thats the path in code

**Comment by anandgp** [comment]
thank you all it's working now @kzawadi , @su-khi 
@ketanchoyal thankyou for this amazing work
