### ISSUE TITLE
Is there WebPortal exists?

### ISSUE THREAD

**Issue by kashifgrocerkey** [ketanchoyal/Academic-Connect#7]
Hi Ketanchoyal, I have installed your app and setup firebase by following screenshots you attached. my question is is there webportal exists which helps in creating a school?

**Comment by ketanchoyal** [comment]
For now no there isn’t any, I’m working on that. Currently you’ve to add login data manually to make app work

**Comment by kashifgrocerkey** [comment]
by manually you means add data in firebase database manually? like "Create a school", i need to add it firebase database manually?

**Comment by ketanchoyal** [comment]
Yes, you’ve to add school code, login data of teacher, parent and student with there corresponding id. (Data structure can be seen in screenshots I’ve added)

**Comment by kashifgrocerkey** [comment]
thanks @ketanchoyal , any thought when webportal will be ready?

**Comment by ketanchoyal** [comment]
Not sure as I’m not getting enough time to work on it, maybe I’ll at least make a portal to add basic data soon and I’ll add any other extra features later on one by one.

**Comment by kashifgrocerkey** [comment]
yeah that will be good enough to get start, if you create basis and I or any other developer extends functionality in it

**Comment by ketanchoyal** [comment]
@kashifgrocerkey exactly, I'll try to do it as soon as possible.
