### ISSUE TITLE
Struck On Login Screen

### ISSUE THREAD

**Issue by cradlesnatcher** [ketanchoyal/Academic-Connect#9]
It was Structed On Login Screen

**Comment by kzawadi** [comment]
follow the db structure as shown in the included folder named **db structure**

**Comment by cradlesnatcher** [comment]
I have Fixed That But Came Across new problem that when i am updating profile from phone no change reflect in db and it is becoming persistence

**Comment by cradlesnatcher** [comment]
![img_20200417](https://user-images.githubusercontent.com/62703454/79540268-7b9bf900-80a5-11ea-805e-bdeb7a4e422d.png)

**Comment by cradlesnatcher** [comment]
@kzawadi Any update bro

**Comment by kzawadi** [comment]
Please show the login structure so we can see how you have structured your db

**Comment by cradlesnatcher** [comment]
![1](https://user-images.githubusercontent.com/62703454/79638684-6ce83b80-81a4-11ea-97a2-2a8bef1dada8.png)
![2](https://user-images.githubusercontent.com/62703454/79638685-6f4a9580-81a4-11ea-8c70-21acabf7258b.png)
![3](https://user-images.githubusercontent.com/62703454/79638687-71acef80-81a4-11ea-9130-f61147498155.png)
![4](https://user-images.githubusercontent.com/62703454/79638688-74a7e000-81a4-11ea-9776-1e1c4d3b6f70.png)

**Comment by kzawadi** [comment]
From the app logic the chatting system is between teachers and parents not children   and in you fb there's is no parents account associated with a teacher.   Please try to add a parent account as shown in the db provided. Note: the teachers and parents are located in the same collection but the in parents doc there is a field named isAteacher which has to be false for parents

**Comment by cradlesnatcher** [comment]
Now I came Up With New Issue That when ever i am updating profile from it is not showing in db and when i am changing in dB not reflecting in phone. Where That changes are saving god knows..

**Comment by kzawadi** [comment]
have you activated firebase storage

**Comment by cradlesnatcher** [comment]
Yaa Firebase Storage is activated

**Comment by kzawadi** [comment]
Okay provide your debug information when this error occurs

**Comment by cradlesnatcher** [comment]
Please Provide Complete Database Structure Of Profile, Chats, Post, Assignments And All Other Stuff
@kzawadi

**Comment by kzawadi** [comment]
@cradlesnatcher all those mentioned are created pro grammatically    ...you have to only create the login flow and remember to upload the firebase functions

**Comment by cradlesnatcher** [comment]
Thanks You so much bro for helping me out now @kzawadi you can close this Issue But before that kindly tell us when we are gong to see next update from @ketanchoyal .

**Comment by kzawadi** [comment]
Soon and very soon   but i am sure your also aware of the current world situations and also he is doing some exams...your prayers will be appreciated too so he can do it better by the power of GOD    @ketanchoyal

**Comment by kzawadi** [comment]
You opened the issue so close it

**Comment by ketanchoyal** [comment]
Thanks @kzawadi for your support
